name: Run Fuzzer on Push to Main

on:
  push:
    branches:
      - main

jobs:
  run-fuzzer:
    name: Run Fuzzer
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the html_parser executable
      - name: Build html_parser
        run: |
          chmod +x ./html_parser
          echo "html_parser built successfully"

      # Step 4: Compile the Fuzzer program
      - name: Compile Fuzzer
        run: javac Fuzzer.java

      # Step 5: Run the Fuzzer
      - name: Run Fuzzer against html_parser
        run: |
          java Fuzzer ./html_parser
        continue-on-error: false  # Fail the workflow if the fuzzer returns a non-zero exit code